<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>3e09497e-e664-4b0b-97c5-625b8e3f17bc</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0.5  ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
