<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>e86d2ecf-b4f0-4bc7-8034-ebd2ba2fd26d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0.5 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
